[package]
name = "RustyPython"
version = "0.1.0"
edition = "2021"

[dependencies]
peg = "0.8.4"
strum = "0.26.3"
strum_macros = "0.26.4"
mopa = "0.2.2"
ahash = "0.8.11"

[profile.release]
debug = true

[features]
trace = ["peg/trace"]
